config/routes.rb
Rails.application.routes.draw do
 
 resources :topics, only: [:index, :show] 

  resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
    end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'ruby-items', to: 'portfolios#ruby'



  get '/about', to: 'pages#about'

  get '/contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do 
  member do 
    get :toggle_status
  end
end
  
mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
<%= js add_gritter(flash[:alert], :title =>  "Jack Leonard", sticky: false, time: 500) %>

<% elsif flash[:error] %>
<%= js add_gritter(flash[:error], :title =>  "Jack Leonard", sticky: false) %>

<% else %>
<%= js add_gritter(flash[:notice], :title =>  "Jack Leonard", sticky: false, time: 500) %>
<% end %>

app/views/shared/_application_footer.html.erb
 <div class="mastfoot">
            <div class="inner">
              <p class="app-footer"><%= copyright_generator %></p>
            </div>
          </div>

app/views/shared/_application_nav.html.erb
 <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Jack Leonard</h3>
              <nav class="nav nav-masthead app-nav">
        <%= nav_helper 'nav-link', 'span' %>
         <%= login_helper 'nav-link' %>
                
              </nav>
            </div>
          </div>

app/views/shared/_blog_footer.html.erb
          <footer class="blog-footer">
      <p><%= copyright_generator%>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

app/views/shared/_blog_masthead.html.erb
   <div class="blog-header">
      <div class="container">
        <h1 class="blog-title">My Blog </h1>
        <p class="lead blog-description"> Technology, Family, and (Anything Else I Find Fun to Share)</p>
        
       <span>
         <%= link_to ' Compose a New Blog', new_blog_path if logged_in?(:site_admin) %>

       </span> 
       <span>
         <%= link_to 'Topic', topics_path %>
       </span>
      </div>
    </div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">
    <%= link_to "Jack Leonard", root_path, class: 'navbar-brand' %>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div>
           <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li' %>  
        <%= login_helper 'nav-link' %>  
      </ul>
      
   
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
        <div class="col-sm-3 offset-sm-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About the Author</h4>
            <p> <em>Jack Leonard</em> Is a lover of all things minimal, antiskoeumophic, minimal, and functional. </p>
          </div>
          
          
              
          
          <div class="sidebar-module">
            <h4> Topics </h4>
            <% @side_bar_topics.each do |topic| %>
            <p> <%= link_to topic.title, topic_path(topic) %> </p>
            <% end %>
            
                <%= source_helper("alert alert-info blog-sidebar-source") %>
          </div>
    
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled social-links">
              <li><a href="https://github.com/jleo13"><%= fa_icon "github" %></a></li>
              <li><a href="#"><%= fa_icon "instagram" %></a></li>
              <li><a href="#"><%= fa_icon "twitter" %></a></li>
            </ol>
          </div>
        </div>
      </div>
      
      

          

app/views/shared/_nav.html.erb
 <div class="<%= location %>">

 
 
  <div>  <%= link_to "Home", root_path, class: 'nav-link' %> </div>
 <div>  <%= link_to "About Me", about_path, class: 'nav-link' %> </div>
 <div>  <%= link_to "Contact", contact_path, class: 'nav-link' %> </div>
 <div>  <%= link_to "Blog", blogs_path, class: 'nav-link' %> </div>
  <div> <%= link_to "Portfolio", portfolios_path, class: 'nav-link' %> </div>
 <div>  <%= login_helper 'nav-link' %> </div><%= login_helper 'nav-link' %> </div>
                 
   
  </div>

app/views/shared/_portfolio_footer.html.erb
    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <%= link_to "View All Portfolio Items", portfolios_path %> /
          <a href="#">Back to top</a>
        </p>
     <p>
       <%= copyright_generator %>
     </p>
      </div>
    </footer>

app/views/shared/_portfolio_masthead.html.erb
 <section class="jumbotron text-center">
      <div class="container">

        <h1 class="jumbotron-heading">My Portfolio</h1>
        <p class="lead text-muted"> Here you can find (almost) anything I have created using my technology skills. Some of these may be film projects, school projects or programming side-jobs. Hope you enjoy.</p>
        <p>
         <%= link_to "About Me",  about_path, class: "btn btn-primary"%>
          <%= link_to "Blogs",  blogs_path, class: "btn btn-secondary"%>
        </p>
      </div>
    </section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Jack Leonard's Personal Portfolio of acheivments relating to technology. Projects include: award-winning French-film Mauvais Presage, a load of anti-skeoumorphic, minimal avatars created for Avatar By Jack, a website owned and managed by Jack, and Doughnut Danger, an application that won 3rd place in a local app competition.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Contact</h4>
        <ul class="list-unstyled">
        <%= nav_helper 'text-white', 'li' %>
  <li> <%= login_helper 'text-white' %> </li>
        </ul>
      </div>
    </div>
  </div>
</div>
   
    
    
      <div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Jack Leonard</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>